# Generated by Django 4.1.7 on 2023-03-12 14:57

import color_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('red', models.IntegerField(validators=[color_app.validators.color_channel_validator])),
                ('green', models.IntegerField(validators=[color_app.validators.color_channel_validator])),
                ('blue', models.IntegerField(validators=[color_app.validators.color_channel_validator])),
            ],
        ),
    ]
